### ISSUE TITLE
Déplacez le contenu du dossier std2024

### ISSUE THREAD

**Issue by BrianPulfer** [YvyTheTardigrade/std2024#1]
Cher étudiant,

Pour que le workflow de test fonctionne correctement, vous devez déplacer tout le contenu de `std2024` dans le dossier principal de ce repo. Après avoir déplacé tout le contenu, ajoutez vos modifications avec `git add .`, fait un commit avec `git commit -m "message"` et fait un push avec `git push`.

**Comment by YvyTheTardigrade** [comment]
Merci, cela as été fait.
